services:
  tooly-auth-db:
    image: postgres:16
    container_name: tooly-auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tooly_rent_auth
    ports:
      - "5433:5432"
    volumes:
      - tooly_auth_pg:/var/lib/postgresql/data
  tooly-user-db:
    image: postgres:16
    container_name: tooly-user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tooly_rent_user
    ports:
      - "5434:5432"
    volumes:
      - tooly_user_pg:/var/lib/postgresql/data
  tooly-listing-db:
    image: postgres:16
    container_name: tooly-listing-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tooly_rent_listing
    ports:
      - "5435:5432"
    volumes:
      - tooly_listing_pg:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tooly_rent_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  tooly_auth_pg:
  tooly_user_pg:
  tooly_listing_pg:
  rabbitmq_data:
