services:
  tooly-auth-db:
    image: postgres:16
    container_name: tooly-auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tooly_rent_auth
    ports:
      - "5433:5432"
    volumes:
      - tooly_auth_pg:/var/lib/postgresql/data

volumes:
  tooly_auth_pg:
